fix classpath that caused for: Caused by: java.lang.NoSuchMethodError: org.objectweb.asm.ClassVisitor.visit(ILjava/lang/String;Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;)V 	at net.sf.cglib.core.ClassEmitter.begin_class(ClassEmitter.java:101)
svn path=/xap/trunk/openspaces/; revision=135926


Former-commit-id: 4e4a5df78c979196c23b96aff56ff7373b0a3af6